version: '3.8'                                          # file format version

services:                                               # define services (containers)
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
    image: mariadb_image                                # after build docker will tag image as name
    restart: always                                     # if container stops or server reboots docker automatically restarts container
    env_file: .env                                      # loads env vars from file
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
      MYSQL_DATABASE: ${WORDPRESS_DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
    volumes:                                            # if container is deleted without a volume you lose your database
      # - ${HOME}/data/mariadb:/var/lib/mysql             # where mariadb stores it's database filesdoc, previously mariadb_data:/var/lib/mysql
      - mariadb_data:/var/lib/mysql 
    networks:
      - inception                                       # attaches mariadb container to custom docker network
    secrets:
      - db_root_password
      - db_user_password
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress_image
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WORDPRESS_DB_HOST: mariadb:3306                   # default port for mariadb and mysql servers listen for database connections
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
    volumes:
      # - ${HOME}/data/wordpress:/var/www/html            # previously wordpress_data:/var/www/html
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_user_password

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx_image
    restart: always
    depends_on:
      - wordpress
    ports:                                              # host:container format  host: host machine port(laptop/vm) container: container's port (inside nginx container)
     - "443:443"                                        # binds containers port to host machine's port
    volumes:
      # - ${HOME}/data/wordpress:/var/www/html             # Both need wordpress_data because they both work on the same WordPress website files, but for different reasons (PHP execution vs web serving), previously wordpress_data:/var/www/html 
      - wordpress_data:/var/www/html 
    networks:
      - inception
    
volumes:                                                # defines named persistent storage volumes, safe storage surviving container restarts/rebuilds
  mariadb_data:                                         # store database files outside container filesystem so when container is deleted or rebuilt, no important data is lost
  wordpress_data:                                       # store wordpress website files (php code, images uploaded etc)

networks:                                               # defines private network connecting containers
  inception:
    driver: bridge                                      # default nework driver for isolated private communication inside single docker host containers on the same bridge can talk by name (not IP) outside containers cant reach unless expose port

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
